apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  initContainers:
    - name: wait-for-db
      image: busybox
      command: ['sh', '-c']
      args:
        - until wget -q http://db; do echo waiting for db; sleep 5; done
  containers:
    - name: app
      image: nginx